[metadata]
name = decbin
version = 0.0.1
requires_python = >=3.8

[options]
install_requires =
    torch>=1.10
    numpy
    pandas
    scikit-learn
    hyperopt
    biopython
    tqdm
    tabulate
    matplotlib

[options.entry_points]
console_scripts =
    decbin-run = decbin.dec_train:main
    decbin-pretrain = decbin.vae_pretrain:main
